SYMBOLS = [
    "BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "XRPUSDT", "DOGEUSDT", "ADAUSDT", "AVAXUSDT", "LINKUSDT", "LTCUSDT",
    "BCHUSDT", "DOTUSDT", "TRXUSDT", "SUIUSDT", "APTUSDT", "NEARUSDT", "INJUSDT", "ATOMUSDT", "FILUSDT", "ETCUSDT",
    "ARBUSDT", "OPUSDT", "UNIUSDT", "AAVEUSDT", "SEIUSDT", "TIAUSDT", "RENDERUSDT", "FETUSDT", "PEPEUSDT", "WIFUSDT",
]
